Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -54,7 +54,7 @@ jobs:
       - name: Generate Allure Report
         run: |
           mkdir -p TestResults
-          allure generate TestResults --clean -o ./allure-report
+          allure generate TestResults --clean -o ./allure-report || echo "Allure report generation failed"
           ls -la ./allure-report
 
       - name: Upload Allure Report Artifact
@@ -86,7 +86,7 @@ jobs:
           
       - name: Merge Allure Reports
         run: |
-          allure generate combined-allure-report --clean -o final-allure-report
+          allure generate combined-allure-report --clean -o final-allure-report echo "Allure merge failed"
 
       - name: Upload Final Merged Allure Report
         uses: actions/upload-artifact@v4
